hotel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('hotelapp.urls')),
    path('admin/', admin.site.urls),
]

hotelapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'hotelapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('pokoje/<int:room_id>/', views.room_view, name='room'),
    path('pokoje/', views.search_rooms, name='rooms'),
    path('rejestracja/', views.guest_register, name='register'),
    path('logowanie/', views.guest_login, name='login'),
    path('wyloguj/', views.guest_logout, name='logout'),
    path('dodaj-rezerwacje/', views.guest_add_reservation, name='add_reservation'),
    path('moje-rezerwacje/', views.my_reservations, name='my_reservations'),
    path('zarzadzaj-rezerwacjami/', views.manage_reservations, name='manage_reservations'),
    path('zarzadzaj-goscmi/', views.manage_guests, name='manage_guests'),
    path('statistics/', views.statistics, name='statistics'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelapp/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

from .period import Period


class User(AbstractUser):
    pass


class Guest(User):
    phone_number = models.CharField(max_length=255, default=None, blank=True, null=True)

    def has_perm(self, perm, obj=None):
        if perm == 'add_reservation_for_self':
            return True

        return False


class Receptionist(User):
    phone_number = models.CharField(max_length=255, default=None, blank=True, null=True)
    pesel = models.CharField(max_length=11, default=None, blank=True, null=True)
    address = models.CharField(max_length=255, default=None, blank=True, null=True)


class Hotel(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024, default=None, blank=True, null=True)
    stars = models.IntegerField(default=None, blank=True, null=True)
    localization = models.CharField(max_length=1024, default=None, blank=True, null=True)
    email = models.CharField(max_length=255, default=None, blank=True, null=True)
    phone_number = models.CharField(max_length=64, default=None, blank=True, null=True)

    @staticmethod
    def get_hotel():
        try:
            return Hotel.objects.all()[0]
        except (IndexError, Hotel.DoesNotExist):
            return None


class HotelImage(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField()

    @property
    def url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url


class Room(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024, default=None, blank=True, null=True)
    room_number = models.IntegerField()
    price_for_night = models.IntegerField()
    guests_count = models.IntegerField()
    photo = models.ImageField(upload_to='images/rooms', default=None, blank=True, null=True)


class DateNotAvailableException(Exception):
    pass


class TooMuchGuestsException(Exception):
    pass


class Reservation(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    creation_date = models.DateField()
    creation_time = models.TimeField()
    payment_status = models.BooleanField(default=False)
    bill = models.IntegerField()
    guests_count = models.IntegerField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)

    def period(self):
        return Period(self.start_date, self.end_date)

    def period_available(self):
        reservations = ReservationActive.objects.filter(room=self.room).exclude(pk=self.pk)

        for r in reservations:
            if self.period().overlaps(r.period()):
                return False

        return True

    @staticmethod
    def income(period):
        reservations = Reservation.objects.all()

        income = 0

        for r in reservations:
            if r.start_date >= period.start and r.end_date <= period.end:
                income = income + r.bill

        return income


class ReservationActive(Reservation):
    def save(self, *args, **kwargs):
        if not self.period_available():
            raise DateNotAvailableException('Date not available.')

        if self.guests_count > self.room.guests_count:
            raise TooMuchGuestsException('Too much guests for this room.')

        self.creation_date = timezone.now().date()
        self.creation_time = timezone.now().time()

        self.bill = (self.period().length().days - 1) * self.room.price_for_night

        super().save(*args, **kwargs)

    class Meta:
        permissions = [
            ("add_reservation_for_self", "Can add reservation for self"),
            ("change_payment_status", "Can change reservation's payment status"),
            ("deactivate", "Can deactivate reservation"),
        ]


class ReservationInactive(Reservation):
    pass

hotelapp/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db import IntegrityError

from .period import DateRangeException, Period

from .models import *

from django.core.validators import validate_integer

from .templatetags.custom_tags import get_today, get_tomorrow


def index(request):
    context = dict()

    try:
        hotel = Hotel.get_hotel()
        context['hotel_images'] = hotel.images.all()
    except Hotel.DoesNotExist:
        pass

    return render(request, 'hotelapp/index.html', context)


def get_rooms_available_in(rooms, period):
    rooms_available = []
    for r in rooms:
        room_reservations = ReservationActive.objects.filter(room=r)

        colliding_reservations = [res for res in room_reservations if period.overlaps(res.period())]

        if not colliding_reservations:
            rooms_available.append(r)

    return rooms_available


def search_rooms(request):
    context = dict()

    context['errors'] = []
    context['date_start'] = request.POST.get('date_start', get_today())
    context['date_end'] = request.POST.get('date_end', get_tomorrow())
    context['guests_count'] = request.POST.get('guests_count')

    try:
        guests_count = request.POST['guests_count']

        validate_integer(guests_count)

        rooms_to_show = Room.objects.filter(guests_count__gte=guests_count).order_by('guests_count')
    except (KeyError, ValidationError):
        rooms_to_show = Room.objects.all()

    try:
        period = Period(
            datetime.strptime(request.POST['date_start'], '%Y-%m-%d').date(),
            datetime.strptime(request.POST['date_end'], '%Y-%m-%d').date()
        )
        rooms_to_show = get_rooms_available_in(rooms_to_show, period)
    except KeyError:
        pass
    except DateRangeException:
        context['errors'].append('Start date has to be before end date')

    context['rooms'] = rooms_to_show

    return render(request, 'hotelapp/rooms.html', context)


def room_view(request, room_id):
    context = {
        'room': get_object_or_404(Room, pk=room_id)
    }

    context['date_start'] = request.POST.get('date_start', get_today())
    context['date_end'] = request.POST.get('date_end', get_tomorrow())

    context['guests_count'] = request.POST.get('guests_count')

    return render(request, 'hotelapp/room.html', context)


def guest_register(request):
    context = {
        'errors': []
    }

    try:
        Guest.objects.get(email=request.POST['email'])
        context['errors'].append('The user with that email already exists. Try to log in.')
    except Guest.DoesNotExist:
        try:
            guest = Guest.objects.create_user(
                username=request.POST['email'],
                email=request.POST['email'],
                password=request.POST['password'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name']
            )
        except KeyError:
            context['errors'].append('You should fill all required data.')
            return render(request, 'hotelapp/register.html')

        try:
            guest.phone_number = request.POST['phone_number']
            guest.save()
        except KeyError:
            pass

        return redirect(reverse('hotelapp:login'))
    except KeyError:
        pass

    return render(request, 'hotelapp/register.html', context)


def guest_login(request):
    context = {
        'errors': []
    }

    try:
        email = request.POST['email']
        password = request.POST['password']

        try:
            user = authenticate(request, username=email, password=password)

            if user is not None:
                login(request, user)
                return redirect(reverse('hotelapp:rooms'))

        except (User.DoesNotExist):
            pass

        context['errors'].append('Bad credentials')

    except KeyError:
        pass

    return render(request, 'hotelapp/login.html', context)


def guest_logout(request):
    logout(request)
    return redirect(reverse('hotelapp:index'))


def guest_add_reservation(request):
    if not request.user.is_authenticated:
        request.session['reservation_quited'] = request.POST
        return redirect(reverse('hotelapp:login'))

    context = {
        'errors': [],
        'successes': []
    }

    try:
        room = Room.objects.get(pk=request.POST.get('room_id'))
    except (Room.DoesNotExist, ValueError):
        return redirect(reverse('hotelapp:index'))

    try:
        to_date = lambda s: datetime.strptime(s, '%Y-%m-%d').date()
        date_start = to_date(request.POST.get('date_start'))
        date_end = to_date(request.POST.get('date_end'))
        period = Period(date_start, date_end)
    except (DateRangeException, TypeError):
        return redirect(reverse('hotelapp:index'))

    guests_count = int(request.POST.get('guests_count'))

    if request.POST.get('confirmed', 0) == '1':
        try:
            try:
                res = ReservationActive(
                    room=room,
                    guest=Guest.objects.get(user_ptr_id=request.user.pk),
                    start_date=period.start,
                    end_date=period.end,
                    guests_count=guests_count
                )
                res.save()
                return redirect(reverse('hotelapp:my_reservations'))

            except DateNotAvailableException:
                context['errors'].append('Room is not available in this period.')
            except TooMuchGuestsException:
                context['errors'].append('Too much guests for this room.')
            except Guest.DoesNotExist:
                context['errors'].append('You are not a guest.')


        except KeyError:
            context['errors'].append('You did not fill all the required data')

    context['room'] = room
    context['date_start'] = date_start.strftime("%Y-%m-%d") if date_start is not None else get_today()
    context['date_end'] = date_end.strftime("%Y-%m-%d") if date_end is not None else get_tomorrow()
    context['guests_count'] = guests_count if guests_count is not None else room.guests_count

    return render(request, 'hotelapp/add_reservation.html', context)


def my_reservations(request):
    if not request.user.is_authenticated:
        return redirect(reverse('hotelapp:login'))

    try:
        Guest.objects.get(user_ptr_id=request.user.pk)
    except Guest.DoesNotExist:
        return redirect(reverse('hotelapp:login'))

    context = dict()

    try:
        guest = Guest.objects.get(user_ptr_id=request.user.pk)
        context['reservations'] = ReservationActive.objects.filter(guest=guest)
    except Guest.DoesNotExist:
        return redirect(reverse('hotelapp:index'))

    return render(request, 'hotelapp/my_reservations.html', context)


def manage_reservations(request):
    if not request.user.is_authenticated:
        return redirect(reverse('hotelapp:login'))

    try:
        Receptionist.objects.get(user_ptr_id=request.user.pk)
    except Receptionist.DoesNotExist:
        if not request.user.is_superuser:
            return redirect(reverse('hotelapp:login'))
        pass

    reservations = ReservationActive.objects.all()

    try:
        guest_id = int(request.GET['guest_id'])
        reservations.filter(guest=Guest.objects.get(pk=guest_id))
    except KeyError:
        pass

    context = {
        'reservations': reservations,
        'errors': [],
        'successes': []
    }

    if request.POST.get('form_sent', 0) == '1':
        try:
            reservation = ReservationActive.objects.get(pk=int(request.POST.get('reservation_id')))
            guests_count = int(request.POST.get('guests_count'))
            payment_status = True if request.POST.get('payment_status') == 'paid' else False

            reservation.guests_count = guests_count
            reservation.payment_status = payment_status

            reservation.save()

            context['successes'].append('The reservation has been modified.')

        except ReservationActive.DoesNotExist:
            context['errors'].append('Reservation does not exist.')

    return render(request, 'hotelapp/manage_reservations.html', context)


def manage_guests(request):
    if not request.user.is_authenticated:
        return redirect(reverse('hotelapp:login'))

    try:
        Receptionist.objects.get(user_ptr_id=request.user.pk)
    except Receptionist.DoesNotExist:
        if not request.user.is_superuser:
            return redirect(reverse('hotelapp:login'))
        pass

    context = {
        'guests': Guest.objects.all(),
        'errors': [],
        'successes': []
    }

    if request.POST.get('form_sent', 0) == '1':
        try:
            guest = Guest.objects.get(pk=int(request.POST.get('guest_id')))
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')

            guest.first_name = first_name
            guest.last_name = last_name
            guest.username = email
            guest.email = email
            guest.phone_number = phone_number

            guest.save()

            context['successes'].append('The guest has been modified.')

        except Guest.DoesNotExist:
            context['errors'].append('Guest does not exist.')
        except IntegrityError:
            context['errors'].append('This email is not available.')


    return render(request, 'hotelapp/manage_guests.html', context)

def statistics(request):
    if not request.user.is_authenticated:
        return redirect(reverse('hotelapp:login'))

    if not request.user.is_superuser:
        return redirect(reverse('hotelapp:login'))

    context = dict()

hotelapp/templates/hotelapp/add_reservation.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
<div class="container">
    <form class="form-signin col-md-5" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Złóż rezerwację</h1>
        <div class="input-group-addon">Pokój:</div>
        <input type="text" id="inputRoomName" name="room_name" class="form-control" value="{{ room.name }}" required disabled>
        <input type="hidden" id="inputRoomId" name="room_id" class="form-control" value="{{ room.id }}" required readonly>
        <br>
        <div class="input-group-addon">Od: &nbsp;</div>
        <input type="date" id="start" name="date_start"
               value="{{ date_start }}" required readonly>
        <br> <br>
        <div class="input-group-addon">Do: &nbsp;</div>
        <input type="date" id="end" name="date_end"
               value="{{ date_end }}" required readonly>
        <br> <br>
        <div class="input-group-addon">Liczba gości:</div>
        <input type="number" min="1" max="{{ room.guests_count }}" name="guests_count"
               value="{{ guests_count }}" required readonly>
        <input type="hidden" name="confirmed" value="1">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Potwierdź rezerwację</button>
    </form>
</div>

{% endblock %}

hotelapp/templates/hotelapp/base.html
<!doctype html>

{% load static %}
{% get_hotel as hotel %}
{% get_stars as stars %}
{% get_user_type as user_type %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{* static 'images/favicon.ico' *}">


    <title>
        {% block page_title %}
            {% if hotel %}
                {{ hotel.name }}
            {% endif %}
        {% endblock %}
    </title>

    <link href="{% static 'hotelapp/assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'hotelapp/assets/css/hotelapp.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'hotelapp:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>{{ hotel.name }}</strong>
            </a>
            <div class="nav-item dropdown">
                <a class="btn btn-secondary" href="#" id="dropdown-menu" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false"><span class="navbar-toggler-icon"></span></a>
                <div class="dropdown-menu" aria-labelledby="dropdown-menu">
                    {% if not user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'hotelapp:login' %}">Zaloguj się</a>
                    <a class="dropdown-item" href="{% url 'hotelapp:register' %}">Zarejestruj się</a>
                    {% else %}
                    {% if user_type == 'guest' %}
                    <a class="dropdown-item" href="{% url 'hotelapp:my_reservations' %}">Moje rezerwacje</a>
                    {% elif user_type == 'receptionist' or user.is_superuser%}
                    <a class="dropdown-item" href="{% url 'hotelapp:manage_reservations' %}">Zarządzaj rezerwacjami</a>
                    <a class="dropdown-item" href="{% url 'hotelapp:manage_guests' %}">Zarządzaj gośćmi</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'hotelapp:statistics' %}">Statystyki</a>
                        {% endif %}
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'hotelapp:logout' %}">Wyloguj się</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>


<main role="main">
    {% block errors %}
    {% for error in errors %}
    <div class="alert alert-warning" role="alert">
        {{ error }}
    </div>
    {% endfor %}
    {% endblock %}

    {% block successes %}
    {% for s in successes %}
    <div class="alert alert-success" role="alert">
        {{ s }}
    </div>
    {% endfor %}
    {% endblock %}

    {% block main_content %}
    {% endblock %}
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Wróć na górę</a>
        </p>
        <p> &copy; Copyright Mikołaj Sawicki & Mateusz Dudek</p>
    </div>
</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="assets/js/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'hotelapp/assets/js/popper.min.js' %}"></script>
<script src="{% static 'hotelapp/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'hotelapp/assets/js/holder.min.js' %}"></script>

</body>
</html>

hotelapp/templates/hotelapp/index.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ hotel.name }}</h1>
        {% if stars %}
        <span class="text-warning">{{ stars |safe }}</span> <br> <br>
        {% endif %}
        <p class="lead text-muted">{{ hotel.description }}</p>
        <p>
            <a href="{% url 'hotelapp:rooms' %}" class="btn btn-primary my-2">Przeglądaj pokoje</a>
        </p>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for image in hotel_images %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ image.url }}" alt="Zdjęcie hotelu">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

hotelapp/templates/hotelapp/login.html
{% extends "hotelapp/base.html" %}

{% block main_content %}


<div class="container">
  <form class="form-signin col-md-5" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Zaloguj się</h1>
    <label for="inputEmail" class="sr-only">Adres e-mail</label>
    <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Adres e-mail" required autofocus>
    <label for="inputPassword" class="sr-only">Hasło</label>
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Hasło" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Zaloguj się</button>
  </form>
</div>

{% endblock %}

hotelapp/templates/hotelapp/manage_guests.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
<div class="container">
    <br><br>
    <h1>Goście</h1>

    {% for guest in guests %}
    <br>
    <div class="col-md-6">
        <h3>Gość</h3>
        <form method="post">
            {% csrf_token %}
            <hr>
            <input type="hidden" class="form-control" value="{{ guest.id }}" name="guest_id">
            <br>
            <div class="input-group-addon">Imię:</div>
            <input type="text" value="{{ guest.first_name }}" name="first_name">
            <br><br>
            <div class="input-group-addon">Nazwisko:</div>
            <input type="text" value="{{ guest.last_name }}" name="last_name">
            <br><br>
            <input type="email" value="{{ guest.email }}" name="email">
            <input type="phone" value="{{ guest.phone_number }}" name="phone_number">
            <input type="hidden" name="form_sent" value="1">
            <br><br>
            <a href="{% url 'hotelapp:manage_reservations' %}?guest_id={{ guest.id }}">Rezerwacje gościa</a>
            <br><br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Zapisz gościa</button>
            <hr>
        </form>
    </div>
    {% endfor %}
</div>

{% endblock %}

hotelapp/templates/hotelapp/manage_reservations.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
<div class="container">
    <br><br>
    <h1>Rezerwacje</h1>

    {% for reservation in reservations %}
    <br>
    <div class="col-md-6">
        <h3>Rezerwacja</h3>
        <form method="post">
            {% csrf_token %}
            <hr>
            <div class="input-group-addon">Pokój:</div>
            <input type="text" class="form-control" value="{{ reservation.room.name }}"
                   disabled>
            <input type="hidden" class="form-control" value="{{ reservation.id }}" name="reservation_id" readonly>
            <br>
            <div class="input-group-addon">Imię gościa:</div>
            <input type="text" value="{{ reservation.guest.first_name }}" disabled>
            <br><br>
            <div class="input-group-addon">Nazwisko gościa:</div>
            <input type="text" value="{{ reservation.guest.last_name }}" disabled>
            <br><br>
            <div class="input-group-addon">Od: &nbsp;</div>
            <input type="text" id="start" value="{{ reservation.start_date }}" disabled>
            <br> <br>
            <div class="input-group-addon">Do: &nbsp;</div>
            <input type="text" id="end" value="{{ reservation.end_date }}" disabled>
            <br> <br>
            <div class="input-group-addon">Liczba gości:</div>
            <input type="number" value="{{ reservation.guests_count }}" name="guests_count">
            <br><br>
            <div class="input-group-addon">Rachunek:</div>
            <input type="number" value="{{ reservation.bill }}" disabled>
            <br><br>
            <div class="input-group-addon">Opłacona:</div>
            <input type="checkbox" value="paid" {% if reservation.payment_status %} checked {% endif %}
                   name="payment_status">
            <input type="hidden" name="form_sent" value="1">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Zapisz rezerwację</button>
            <hr>
        </form>
    </div>
    {% endfor %}
</div>

{% endblock %}

hotelapp/templates/hotelapp/room.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
{% get_today as today %}
{% get_tomorrow as tomorrow %}

<div class="container">
    <br>
    <div class="filters">

        <h3>Rezerwacja</h3>

        <form action="{% url 'hotelapp:add_reservation' %}" method="post">
            {% csrf_token %}
            <div class="row filters">
                <div class="daterange col-md-4">
                    <label>Czas trwania: </label>
                    <div class="input-group input-daterange">
                        <div class="input-group-addon">Od: &nbsp;</div>
                        <input type="date" id="start" name="date_start"
                               value="{{ date_start }}"
                               min="{% get_today %}" required>
                        <br>
                        <div class="input-group-addon">&nbsp; do: &nbsp;</div>
                        <input type="date" id="end" name="date_end"
                               value="{{ date_end }}"
                               min="{% get_tomorrow %}" required>
                    </div>
                </div>

                <div class="guests_count col-md-4">
                    <label>Liczba gości: </label>
                    <div>
                        <input type="number" min="1" max="10" name="guests_count" placeholder="Liczba gości"
                               value="{{ guests_count }}" required>
                    </div>
                </div>

                <input type="hidden" name="room_id" value="{{ room.id }}">

                <div class="col-md-4">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Zarezerwuj</button>
                </div>
            </div>
        </form>
        <br>
        <div class="col-lg-9">

        <div class="card mt-4">
          <img class="card-img-top img-fluid" src="{{ room.photo.url }}" alt="">
          <div class="card-body">
            <h3 class="card-title">{{ room.name }}</h3>
            <h4>{{ room.price_for_night }}zł za dobę</h4>
              <p class="card-text">{{ room.description }}</p>
          </div>
        </div>
        <!-- /.card -->

      </div>
</div>
{% endblock %}

hotelapp/templates/hotelapp/rooms.html
{% extends "hotelapp/base.html" %}

{% block main_content %}
{% get_today as today %}
{% get_tomorrow as tomorrow %}

<div class="container">
    <br>
    <div class="filters">

        <h3>Filtry</h3>

        <form method="post">
            {% csrf_token %}
            <div class="row filters">
                <div class="daterange col-md-4">
                    <label>Wolne w terminie: </label>
                    <div class="input-group input-daterange">
                        <div class="input-group-addon">Od: &nbsp;</div>
                        <input type="date" id="start" name="date_start"
                               value="{{ date_start }}"
                               min="{% get_today %}">
                        <br>
                        <div class="input-group-addon">&nbsp; do: &nbsp;</div>
                        <input type="date" id="end" name="date_end"
                               value="{{ date_end }}"
                               min="{% get_tomorrow %}">
                    </div>
                </div>

                <div class="guests_count col-md-4">
                    <label>Minimalna liczba gości: </label>
                    <div>
                        <input type="number" min="1" max="10" name="guests_count" placeholder="Liczba gości"
                               value="{{ guests_count }}">
                    </div>
                </div>

                <div class="col-md-4">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Wyszukaj</button>
                </div>

            </div>
        </form>
    </div>
    <br>
    <div class="row">
        {% for room in rooms %}

        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start col-md-6">
                    <strong class="d-inline-block mb-2 text-success"> {{ room.price_for_night }}zł za dobę </strong>
                    <h3 class="mb-0">
                        <a class="text-dark" href="#"> {{ room.name }} </a>
                    </h3>
                    <div class="mb-1 text-muted">{{ room.guests_count }}-osobowy</div>
                    <p class="card-text mb-auto">{{ room.description }}</p>

                    <form action="{% url 'hotelapp:room' room.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="date_start" value="{{ date_start }}">
                        <input type="hidden" name="date_end" value="{{ date_end }}">
                        <input type="hidden" name="guests_count" value="{{ guests_count }}">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Więcej</button>
                    </form>
                </div>
                <img class="card-img-right flex-auto d-none d-md-block col-md-6" src="{{ room.photo.url }}"
                     alt="Card image cap">
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}